config/routes.rb
TraceMyRide::Application.routes.draw do
  get "passengers/index"

  resources :attendences
  resources :passengers

  resources :pick_up_points


  resources :vehicles


  resources :profiles
  resources :vehicles
  devise_for :users, :controllers => { :registrations => "registrations" }
  root :to => 'vehicles#index'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :address, :blood_group, :contact_no, :emergency_contact_no, :family_doctor_name,
                  :profile_title, :ref_number_1, :ref_number_2, :user_id, :photo

  validates_presence_of :address, :blood_group, :contact_no, :emergency_contact_no, :profile_title

  belongs_to :user

  TITLE = %w(driver employee)

  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update_attributes(params[:profile])
    @profile.save
    redirect_to @profile, :notice => "Hahahahaha..."
  end


end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<h2> Update Profile </h2>
<%= form_for(@profile) do |profile| %>
    Upload Photo : <br> <%= profile.file_field :photo %><br>

    Address : <br> <%= profile.text_field :address %><br>

    Contact Number :<br> <%= profile.text_field :contact_no %><br>

    Blood Group : <br><%= profile.text_field :blood_group %><br>

    Emergency Contact Number :<br><%= profile.text_field :emergency_contact_no %><br>

    Family Doctor Name : <br><%= profile.text_field :family_doctor_name %><br>

    First Reference Number :<br><%= profile.text_field :ref_number_1 %><br>

    Second Reference Number : <br><%= profile.text_field :ref_number_2 %><br>

    Select Profile Title : <br><%= profile.select :profile_title, Profile::TITLE %><br><br>

  <%= profile.submit " Update " %>

<% end %>

app/views/profiles/show.html.erb
<style>
#photo{
position: absolute;
width: auto; /*Width of frame div*/
overflow: hidden; /*Disable scrollbars. Set to "scroll" to enable*/
color: green;
padding:10px;
border-radius:10px;
}

#detail{
position: fixed;
left: 400px; /*Set left value to WidthOfFrameDiv*/
overflow: auto;
background: #fff;
}
</style>

<div id = "profile" style ="font-family:ubuntu;margin-top:100px;">
<div id="photo">
  <%= image_tag @profile.photo.url(:small) %><br>
  <h1><%= @profile.user.full_name %></h1>
</div>

<div id ="detail">
  <b><%= link_to "Edit", edit_profile_path(@profile) %></b>
  <h4>Profile Title : <%= @profile.profile_title %></h4><hr>
  Full Address : <%= @profile.address %> <hr>
  Contact Number : <%= @profile.contact_no %> <hr>
  Blood Group : <%= @profile.blood_group %> <hr>
  Emergency Contact Number : <%= @profile.emergency_contact_no %> <hr>
  Family Doctor Name : <%= @profile.family_doctor_name  %> <hr>
  Contact Reference Number_1 : <%= @profile.ref_number_1 %> <hr>
  Contact Reference Number_1 : <%= @profile.ref_number_2 %>
</div>

</div>