config/routes.rb
TraceMyRide::Application.routes.draw do
  get "passengers/index"

  resources :attendences
  resources :passengers

  resources :pick_up_points


  resources :vehicles


  resources :profiles
  resources :vehicles
  devise_for :users, :controllers => { :registrations => "registrations" }
  root :to => 'vehicles#index'
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  attr_accessible :user_id, :vehicle_make, :vehicle_number
  validates_presence_of :user_id, :message => "Please select a driver"
  validates_presence_of :vehicle_make, :vehicle_number
  has_many :pick_up_points
  belongs_to :attendence
  belongs_to :user
  has_many :passengers
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicles }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    @vehicle = Vehicle.find(params[:id])
    @passengers = Passenger.new
    @passenger = Passenger.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/new
  # GET /vehicles/new.json
  def new
    @vehicle = Vehicle.new
    @profiles = Profile.joins(:user).find_all_by_profile_title("driver")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(params[:vehicle])
    @profiles = Profile.joins(:user).find_all_by_profile_title("driver")
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render json: @vehicle, status: :created, location: @vehicle }
      else
        format.html { render action: "new" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vehicles/1
  # PUT /vehicles/1.json
  def update
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      if @vehicle.update_attributes(params[:vehicle])
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :Select_Driver %><br />
    <%= f.select :user_id, @profiles.collect {|p| [ p.user.full_name, p.id ] }, {include_blank: 'None'} %>
  </div>

  <div class="field">
    <%= f.label :vehicle_make %><br />
    <%= f.text_field :vehicle_make, :placeholder => "eg. Tata Indica, Toyota etios" %>
  </div>
  <div class="field">
    <%= f.label :vehicle_number %><br />
    <%= f.text_field :vehicle_number, :placeholder => "eg. MH-03 BG- 7661" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Listing vehicles</h1>

<table>
  <tr>
    <th>Vehicle make</th>
    <th>Vehicle number</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vehicles.each do |vehicle| %>
  <tr>
    <td><%= vehicle.vehicle_make %></td>
    <td><%= vehicle.vehicle_number %></td>
    <td><%= vehicle.user_id %></td>
    <td><%= link_to 'Show', vehicle %></td>
    <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
    <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Vehicle make:</b>
  <%= @vehicle.vehicle_make %>
</p>

<p>
  <b>Vehicle number:</b>
  <%= @vehicle.vehicle_number %>
</p>

<p>
  <b>Driver Name :</b>
  <%= @vehicle.user.full_name %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>
<hr>

<h4> Passengers List </h4>
<table>
<tr>
<% Passenger.find(:all).each do |p| %>
 <td><%= p.user.full_name %></td></tr>
<% end %>
</table>

<%= javascript_include_tag "jquery.tokeninput"%>
<%= stylesheet_link_tag "token-input-facebook", "token-input"%>

<h1> Add Passengers </h1>
<%= form_for @passengers do |f| %>
<%= f.label "Add Passenger" %><br>
<%= text_field_tag "users","", :id =>"demo-input-facebook-theme" %><br>
<%= f.hidden_field :vehicle_id, :value => @vehicle.id %>
<%= f.submit "Add", :class=> "btn btn-info" %>
<% end %>