config/routes.rb
TraceMyRide::Application.routes.draw do
  get "passengers/index"

  resources :attendences
  resources :passengers

  resources :pick_up_points


  resources :vehicles


  resources :profiles
  resources :vehicles
  devise_for :users, :controllers => { :registrations => "registrations" }
  root :to => 'vehicles#index'
end

app/models/pick_up_point.rb
class PickUpPoint < ActiveRecord::Base
  attr_accessible :address, :name

  has_many :users
  belongs_to :attendence
end

app/controllers/pick_up_points_controller.rb
class PickUpPointsController < ApplicationController
  # GET /pick_up_points
  # GET /pick_up_points.json
  def index
    @pick_up_points = PickUpPoint.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pick_up_points }
    end
  end

  # GET /pick_up_points/1
  # GET /pick_up_points/1.json
  def show
    @pick_up_point = PickUpPoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pick_up_point }
    end
  end

  # GET /pick_up_points/new
  # GET /pick_up_points/new.json
  def new
    @pick_up_point = PickUpPoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pick_up_point }
    end
  end

  # GET /pick_up_points/1/edit
  def edit
    @pick_up_point = PickUpPoint.find(params[:id])
  end

  # POST /pick_up_points
  # POST /pick_up_points.json
  def create
    @pick_up_point = PickUpPoint.new(params[:pick_up_point])

    respond_to do |format|
      if @pick_up_point.save
        format.html { redirect_to @pick_up_point, notice: 'Pick up point was successfully created.' }
        format.json { render json: @pick_up_point, status: :created, location: @pick_up_point }
      else
        format.html { render action: "new" }
        format.json { render json: @pick_up_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pick_up_points/1
  # PUT /pick_up_points/1.json
  def update
    @pick_up_point = PickUpPoint.find(params[:id])

    respond_to do |format|
      if @pick_up_point.update_attributes(params[:pick_up_point])
        format.html { redirect_to @pick_up_point, notice: 'Pick up point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pick_up_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pick_up_points/1
  # DELETE /pick_up_points/1.json
  def destroy
    @pick_up_point = PickUpPoint.find(params[:id])
    @pick_up_point.destroy

    respond_to do |format|
      format.html { redirect_to pick_up_points_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pick_up_points_helper.rb
module PickUpPointsHelper
end

app/views/pick_up_points/_form.html.erb
<%= form_for(@pick_up_point) do |f| %>
  <% if @pick_up_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pick_up_point.errors.count, "error") %> prohibited this pick_up_point from being saved:</h2>

      <ul>
      <% @pick_up_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pick_up_points/edit.html.erb
<h1>Editing pick_up_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @pick_up_point %> |
<%= link_to 'Back', pick_up_points_path %>

app/views/pick_up_points/index.html.erb
<h1>Listing pick_up_points</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pick_up_points.each do |pick_up_point| %>
  <tr>
    <td><%= pick_up_point.name %></td>
    <td><%= pick_up_point.address %></td>
    <td><%= link_to 'Show', pick_up_point %></td>
    <td><%= link_to 'Edit', edit_pick_up_point_path(pick_up_point) %></td>
    <td><%= link_to 'Destroy', pick_up_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pick up point', new_pick_up_point_path %>

app/views/pick_up_points/new.html.erb
<h1>New pick_up_point</h1>

<%= render 'form' %>

<%= link_to 'Back', pick_up_points_path %>

app/views/pick_up_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pick_up_point.name %>
</p>

<p>
  <b>Address:</b>
  <%= @pick_up_point.address %>
</p>


<%= link_to 'Edit', edit_pick_up_point_path(@pick_up_point) %> |
<%= link_to 'Back', pick_up_points_path %>