config/routes.rb
TraceMyRide::Application.routes.draw do
  get "passengers/index"

  resources :attendences
  resources :passengers

  resources :pick_up_points


  resources :vehicles


  resources :profiles
  resources :vehicles
  devise_for :users, :controllers => { :registrations => "registrations" }
  root :to => 'vehicles#index'
end

app/models/attendence.rb
class Attendence < ActiveRecord::Base
  attr_accessible :employee_id, :pick_up_point_id, :status, :user_id, :vehicle_id

  has_many :users
  has_many :vehicles
  has_many :pick_up_points

  include Workflow
  workflow_column :status
  workflow do
    state :pending do
      event :submit, :transitions_to => :approved
    end
    state :approved
  end
end

app/controllers/attendences_controller.rb
class AttendencesController < ApplicationController
  # GET /attendences
  # GET /attendences.json
  def index
    @attendences = Attendence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendences }
    end
  end

  # GET /attendences/1
  # GET /attendences/1.json
  def show
    @attendence = Attendence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attendence }
    end
  end

  # GET /attendences/new
  # GET /attendences/new.json
  def new
    @attendence = Attendence.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendence }
    end
  end

  # GET /attendences/1/edit
  def edit
    @attendence = Attendence.find(params[:id])
  end

  # POST /attendences
  # POST /attendences.json
  def create
    @attendence = Attendence.new(params[:attendence])

    respond_to do |format|
      if @attendence.save
        format.html { redirect_to @attendence, notice: 'Attendence was successfully created.' }
        format.json { render json: @attendence, status: :created, location: @attendence }
      else
        format.html { render action: "new" }
        format.json { render json: @attendence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendences/1
  # PUT /attendences/1.json
  def update
    @attendence = Attendence.find(params[:id])

    respond_to do |format|
      if @attendence.update_attributes(params[:attendence])
        format.html { redirect_to @attendence, notice: 'Attendence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendences/1
  # DELETE /attendences/1.json
  def destroy
    @attendence = Attendence.find(params[:id])
    @attendence.destroy

    respond_to do |format|
      format.html { redirect_to attendences_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/views/attendences/_form.html.erb
<%= form_for(@attendence) do |f| %>
  <% if @attendence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendence.errors.count, "error") %> prohibited this attendence from being saved:</h2>

      <ul>
      <% @attendence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :vehicle_id %><br />
    <%= f.number_field :vehicle_id %>
  </div>
  <div class="field">
    <%= f.label :pick_up_point_id %><br />
    <%= f.number_field :pick_up_point_id %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.text_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendences/edit.html.erb
<h1>Editing attendence</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendence %> |
<%= link_to 'Back', attendences_path %>

app/views/attendences/index.html.erb
<h1>Listing attendences</h1>

<table>
  <tr>
    <th>User</th>
    <th>Vehicle</th>
    <th>Pick up point</th>
    <th>Employee</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendences.each do |attendence| %>
  <tr>
    <td><%= attendence.user_id %></td>
    <td><%= attendence.vehicle_id %></td>
    <td><%= attendence.pick_up_point_id %></td>
    <td><%= attendence.employee_id %></td>
    <td><%= attendence.status %></td>
    <td><%= link_to 'Show', attendence %></td>
    <td><%= link_to 'Edit', edit_attendence_path(attendence) %></td>
    <td><%= link_to 'Destroy', attendence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attendence', new_attendence_path %>

app/views/attendences/new.html.erb
<h1>New attendence</h1>

<%= render 'form' %>

<%= link_to 'Back', attendences_path %>

app/views/attendences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @attendence.user_id %>
</p>

<p>
  <b>Vehicle:</b>
  <%= @attendence.vehicle_id %>
</p>

<p>
  <b>Pick up point:</b>
  <%= @attendence.pick_up_point_id %>
</p>

<p>
  <b>Employee:</b>
  <%= @attendence.employee_id %>
</p>

<p>
  <b>Status:</b>
  <%= @attendence.status %>
</p>


<%= link_to 'Edit', edit_attendence_path(@attendence) %> |
<%= link_to 'Back', attendences_path %>